CC = g++-13 -std=gnu++20 -O2 -Wall -Wextra 

.PHONY: a b c d e f g

a: a.cpp
	$(CC) a.cpp

b: b.cpp
	$(CC) b.cpp

c: c.cpp
	$(CC) c.cpp

d: d.cpp
	$(CC) d.cpp

e: e.cpp
	$(CC) e.cpp

f: f.cpp
	$(CC) f.cpp

g: g.cpp
	$(CC) g.cpp